"use client";

import { useMemo, useState, type FormEvent } from "react";
import { assessmentWindows, business } from "@/data/content";
import { activeServices, serviceCategories } from "@/data/services";
import type { AssessmentRequest, PhotoMetadata } from "@/lib/assessment";

const steps = ["Services", "Details", "Visit", "Review"];
const initial: AssessmentRequest = { customerType: "new", name: "", phone: "", email: "", eircode: "", selectedServices: [], notes: "", preferredAssessmentDate: "", preferredAssessmentWindow: "", photos: [], consent: false };

export function AssessmentWizard({ initialService }: { initialService?: string }) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ ...initial, selectedServices: initialService && activeServices.some((service) => service.id === initialService) ? [initialService] : [] });
  const [category, setCategory] = useState(activeServices.find((service) => service.id === initialService)?.category || serviceCategories[0]);
  const [status, setStatus] = useState<{ type: "idle" | "sending" | "success" | "error"; message?: string; reference?: string }>({ type: "idle" });
  const selected = useMemo(() => activeServices.filter((service) => form.selectedServices.includes(service.id)), [form.selectedServices]);
  const update = <K extends keyof AssessmentRequest>(key: K, value: AssessmentRequest[K]) => setForm((current) => ({ ...current, [key]: value }));
  const toggleService = (id: string) => update("selectedServices", form.selectedServices.includes(id) ? form.selectedServices.filter((value) => value !== id) : [...form.selectedServices, id]);
  const canContinue = step === 0 ? form.selectedServices.length > 0 : step === 1 ? Boolean(form.name && form.phone && form.email && form.eircode) : step === 2 ? Boolean(form.preferredAssessmentDate && form.preferredAssessmentWindow) : form.consent;
  const minDate = new Date(Date.now() + 86_400_000).toISOString().split("T")[0];

  async function submit(event: FormEvent) {
    event.preventDefault();
    setStatus({ type: "sending" });
    try {
      const response = await fetch("/api/assessment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to send request.");
      setStatus({ type: "success", message: data.deliveryMode === "development" ? "Validated in local development mode. No external delivery was attempted." : "Your request has been sent to Comfort Cleaning.", reference: data.requestId });
    } catch (error) {
      setStatus({ type: "error", message: error instanceof Error ? error.message : "Unable to send request." });
    }
  }

  if (status.type === "success") return <div className="rounded-[1.5rem] bg-white p-5 text-center shadow-2xl sm:rounded-[2rem] sm:p-12"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-full bg-signal text-2xl">✓</div><p className="eyebrow">Request received</p><h2 className="mt-3 text-2xl font-semibold sm:text-3xl">Thank you, {form.name}.</h2><p className="mx-auto mt-4 max-w-lg break-words text-sm leading-6 text-black/60 sm:text-base">{status.message} Your reference is <strong className="text-ink">{status.reference}</strong>. A manager will review the details before confirming a visit.</p></div>;

  return (
    <form data-assessment-form onSubmit={submit} className="min-w-0 max-w-full overflow-hidden rounded-[1.5rem] bg-white shadow-2xl shadow-black/10 sm:rounded-[2rem]">
      <div className="border-b border-black/10 px-4 py-4 sm:px-8 sm:py-5"><div className="flex items-center gap-1.5 sm:gap-2">{steps.map((label, index) => <div key={label} className="flex min-w-0 flex-1 items-center gap-2"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold ${index <= step ? "bg-signal text-ink" : "bg-black/5 text-black/35"}`}>{index + 1}</span><span className="hidden text-xs font-semibold sm:block">{label}</span></div>)}</div><p className="mt-3 text-xs font-semibold text-black/50 sm:hidden">Step {step + 1} of {steps.length} · {steps[step]}</p></div>
      <div className="min-w-0 p-4 sm:p-8">
        {step === 0 && <fieldset className="min-w-0"><legend className="text-xl font-semibold sm:text-2xl">What can we help with?</legend><p className="mt-2 text-sm leading-6 text-black/55">Choose one or more services. You can explain the details later.</p><div className="-mx-1 mt-5 flex max-w-full gap-2 overflow-x-auto px-1 pb-2 sm:mt-6">{serviceCategories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${item === category ? "bg-ink text-white" : "bg-black/5"}`}>{item}</button>)}</div><div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2">{activeServices.filter((service) => service.category === category).map((service) => <label key={service.id} className={`min-w-0 cursor-pointer rounded-2xl border p-3.5 transition sm:p-4 ${form.selectedServices.includes(service.id) ? "border-signal bg-signal/10" : "border-black/10 hover:border-black/30"}`}><input className="sr-only" type="checkbox" checked={form.selectedServices.includes(service.id)} onChange={() => toggleService(service.id)} /><span className="flex min-w-0 items-start justify-between gap-3"><span className="min-w-0 flex-1"><strong className="block break-words">{service.name}</strong><span className="mt-1 block break-words text-xs leading-5 text-black/50">{service.shortDescription}</span></span><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border ${form.selectedServices.includes(service.id) ? "border-signal bg-signal" : "border-black/20"}`}>{form.selectedServices.includes(service.id) ? "✓" : ""}</span></span></label>)}</div></fieldset>}
        {step === 1 && <fieldset className="min-w-0"><legend className="max-w-full text-xl font-semibold leading-tight sm:text-2xl">Tell us about you and the property</legend><p className="mt-2 text-sm leading-6 text-black/55">Your Eircode is enough for this request. We’ll confirm full location details later.</p><div className="mt-5 grid min-w-0 gap-5 sm:mt-6 sm:grid-cols-2"><Field label="Full name" value={form.name} onChange={(value) => update("name", value)} autoComplete="name" /><Field label="Phone" type="tel" value={form.phone} onChange={(value) => update("phone", value)} autoComplete="tel" /><Field label="Email" type="email" value={form.email} onChange={(value) => update("email", value)} autoComplete="email" /><Field label="Eircode" value={form.eircode} onChange={(value) => update("eircode", value.toUpperCase())} autoComplete="postal-code" /><label className="min-w-0 sm:col-span-2"><span className="field-label">Notes <span className="font-normal text-black/40">(optional)</span></span><textarea className="field min-h-28 max-w-full" value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Tell us about rooms, access, stains or priorities." /></label></div></fieldset>}
        {step === 2 && <fieldset><legend className="text-2xl font-semibold">When should the manager visit?</legend><p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">This is your preferred assessment time, not a confirmed cleaning appointment. The manager will review the property and agree the required cleaning time with you.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label><span className="field-label">Preferred date</span><input className="field" type="date" min={minDate} value={form.preferredAssessmentDate} onChange={(event) => update("preferredAssessmentDate", event.target.value)} required /></label><label><span className="field-label">Preferred time window</span><select className="field" value={form.preferredAssessmentWindow} onChange={(event) => update("preferredAssessmentWindow", event.target.value)} required><option value="">Choose a time</option>{assessmentWindows.map((window) => <option key={window}>{window}</option>)}</select></label><label className="sm:col-span-2"><span className="field-label">Property photos <span className="font-normal text-black/40">(optional, metadata only in this demo)</span></span><input className="field file:mr-4 file:rounded-full file:border-0 file:bg-ink file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white" type="file" accept="image/*" multiple onChange={(event) => { const photos: PhotoMetadata[] = Array.from(event.target.files || []).slice(0, 5).map((file) => ({ name: file.name, size: file.size, type: file.type })); update("photos", photos); }} /><p className="mt-2 text-xs text-black/45">Photo upload storage will be connected with the backend. Files are not transmitted in this demo.</p></label></div></fieldset>}
        {step === 3 && <div><h2 className="text-2xl font-semibold">Review your request</h2><div className="mt-6 grid gap-4 rounded-2xl bg-cream p-5 text-sm sm:grid-cols-2"><Review label="Services" value={selected.map((service) => service.name).join(", ")} /><Review label="Customer" value={`${form.name} · ${form.phone} · ${form.email}`} /><Review label="Property Eircode" value={form.eircode} /><Review label="Preferred assessment" value={`${form.preferredAssessmentDate} · ${form.preferredAssessmentWindow}`} />{form.notes && <Review label="Notes" value={form.notes} />}{form.photos.length > 0 && <Review label="Photos prepared" value={form.photos.map((photo) => photo.name).join(", ")} />}</div><div className="mt-5 rounded-2xl border border-signal/50 bg-signal/10 p-4 text-sm leading-6"><strong>What happens next:</strong> a manager reviews your request, visits the property and confirms the work, required cleaning time and price with you.</div><label className="mt-5 flex cursor-pointer items-start gap-3 text-sm"><input className="mt-1 h-4 w-4 accent-ink" type="checkbox" checked={form.consent} onChange={(event) => update("consent", event.target.checked)} /><span>I agree that Comfort Cleaning may use these details to contact me about this assessment request.</span></label>{status.type === "error" && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{status.message} <a className="font-semibold underline" href={`tel:${business.phoneHref}`}>Call {business.phoneDisplay}</a></div>}</div>}
      </div>
      <div className="grid grid-cols-2 gap-3 border-t border-black/10 bg-cream px-4 py-4 sm:px-8 sm:py-5"><button type="button" className={`button button-ghost w-full !px-4 ${step === 0 ? "invisible" : ""}`} onClick={() => setStep((value) => value - 1)}>Back</button>{step < steps.length - 1 ? <button type="button" className="button button-dark w-full !px-4" disabled={!canContinue} onClick={() => setStep((value) => value + 1)}>Continue <span>→</span></button> : <button type="submit" className="button button-primary w-full !px-3" disabled={!canContinue || status.type === "sending"}>{status.type === "sending" ? "Sending…" : <><span className="sm:hidden">Send request</span><span className="hidden sm:inline">Send assessment request</span></>}</button>}</div>
    </form>
  );
}

function Field({ label, value, onChange, type = "text", autoComplete }: { label: string; value: string; onChange: (value: string) => void; type?: string; autoComplete?: string }) { return <label className="min-w-0"><span className="field-label">{label}</span><input className="field min-w-0 max-w-full" type={type} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} required /></label>; }
function Review({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><span className="mb-1 block text-xs font-semibold uppercase tracking-[.14em] text-black/40">{label}</span><p className="break-words leading-6">{value}</p></div>; }
